apiVersion: apps/v1
kind: Deployment
metadata:
  name: wellcom-backend-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wellcom-backend
  template:
    metadata:
      labels:
        app: wellcom-backend
    spec:
      containers:
      - name: wellcom
        image: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com/wellcom:latest
        ports:
        - containerPort: 8080
        resources:
        # 컨테이너가 사용할 수 있는 리소스의 최대치
          limits:
            cpu: "1"
            memory: "500Mi"
        # 컨테이너가 시작될 때 보장받아야 하는 최소 자원
          requests:
            cpu: "0.5"
            memory: "250Mi"
        env:
        # RDS 시크릿
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-infos
                key: DB_HOST
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-infos
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-infos
                key: DB_PASSWORD
          # JWT 시크릿
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-infos
                key: JWT_SECRET_KEY
          - name: JWT_ACCESS_EXPIRE
            valueFrom:
              secretKeyRef:
                name: jwt-infos
                key: JWT_ACCESS_EXPIRE
          - name: JWT_REFRESH_EXPIRE
            valueFrom:
              secretKeyRef:
                name: jwt-infos
                key: JWT_REFRESH_EXPIRE
          # EMAIL 시크릿
          - name: GOOGLE_EMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mail-infos
                key: GOOGLE_EMAIL_PASSWORD
          # OAUTH 시크릿
          - name: OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: oauth-infos
                key: OAUTH_CLIENT_ID
          - name: OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: oauth-infos
                key: OAUTH_CLIENT_SECRET
          - name: OAUTH_REDIRECT_URL
            valueFrom:
              secretKeyRef:
                name: oauth-infos
                key: OAUTH_REDIRECT_URL
          # S3 IMAGE 시크릿
          - name: S3_IMAGE_BUCKET
            valueFrom:
              secretKeyRef:
                name: s3-image-infos
                key: S3_IMAGE_BUCKET
          - name: S3_IMAGE_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-image-infos
                key: S3_IMAGE_ACCESS_KEY
          - name: S3_IMAGE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: s3-image-infos
                key: S3_IMAGE_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: wellcom-backend-service
spec:
# ClusterIP는 클러스터 내부에서만 접근가능한 Service를 생성
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: wellcom-backend